---
- name: install gb language
  package:
    name: language-pack-en
    state: latest

- name: install vim
  package:
    name: vim
    state: latest

- name: install tmux
  package:
    name: tmux
    state: latest

- name: install git
  package:
    name: git
    state: latest

- name: install zsh
  package:
    name: zsh
    state: latest

- name: install mosh
  package:
    name: mosh
    state: latest

- name: install ctags
  package:
    name: ctags
    state: latest

- name: install virtualenv
  package:
    name: virtualenv
    state: latest
